### PR TITLE
Update nunit.analyzers.nuspec to specify that NUnit.Analyzers v4 is intended to be used with NUnit 4.

### PR DESCRIPTION
**Pull request by andrewimcclement**

### CODE REVIEW

**Comment by Bartleby2718** [comment]
`NUnit.Analyzers` v4 can still be used to help folks _transition_ from NUnit v3 to NUnit v4, so I'm not sure if I agree with this.

**Comment by andrewimcclement** [comment]
It can, but it references classes like ClassicAssert which only exist in NUnit v4, so the messages are often incorrect, even if the majority of quick fixes will be fine.

**Comment by manfred-brands** [comment]
The analyzer works with both NUnit 3 and 4. It detects which version if NUnit is referenced in your project and changes behaviour accordingly.

It has to be used with NUnit 3 to prepare moving to NUnit 4 as the latter has breaking changes, especially regarding message formatting.

**Comment by andrewimcclement** [comment]
By all means suggest an alternative phrasing - I feel v4 is at least more accurate than v3, but we may be able to do better.

**Comment by andrewimcclement** [comment]
We could just say `3+` instead of `3`? Or maybe it is worth being explicit - `for use with v4 or for the purposes of migrating from v3 to v4` or something?

**Comment by manfred-brands** [comment]
3+ is fine. Also mentioning the migration is good.

Where do you say it references `ClassicAssert` when using with v3?
If you mean the `Assert.AreEqual`, those conversion analyzers existed way before there was a `ClassicAssert` class.

The {v4 migration guide](https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html#convert-classic-assert-to-constraint-model) says:

> Caveat: The analyzers only run when the code compiles, so execute and act on the analyzer before upgrading nunit to version 4.0.0!

**Comment by andrewimcclement** [comment]
Oh sure, the analyzers existed, it's just they give an incorrect message (precisely because the message talks about the ClassicAssert class, which doesn't exist in v3). It's just a small peeve.

**Review by Bartleby2718 — APPROVED** [review]

**Review by manfred-brands — APPROVED** [review]
I'm ok with these changes

**Pull request merged**
