### PR TITLE
Use Markdown for CHANGES

### PR DESCRIPTION
**Pull request by Bartleby2718**
- Noticed that this repository uses `CHANGES.txt` even though its content is compatible with Markdown.
- Since the repository is hosted on GitHub, I added a `@` before each username.

### CODE REVIEW

**Review by manfred-brands — CHANGES_REQUESTED** [review]
Thanks for that.

When you rename a file, you need to make sure any references to it are also updated, e.g.:
https://github.com/nunit/nunit.analyzers/blob/master/src/nunit.analyzers/nunit.analyzers.nuspec#L22

```xml
<releaseNotes>See the release notes on https://github.com/nunit/nunit.analyzers/blob/master/CHANGES.txt.</releaseNotes>
```

**Comment by Bartleby2718** [comment]
@manfred-brands That was already done in the initial commit :)

**Review by manfred-brands — APPROVED** [review]
Indeed it was. Sorry that I missed it.

**Review by mikkelbu — APPROVED** [review]
Thanks for the contribution @Bartleby2718. The change looks great. I'll merge it now

**Pull request merged**
