### PR TITLE
NonTestMethodAccessibilityLevelAnalyzer: #147: Should be private

### PR DESCRIPTION
**Pull request by manfred-brands**
Only allow private and protected methods.

### CODE REVIEW

**Comment by Dreamescaper** [comment]
Methods marked with SetUp, Teardown, OneTimeSetUp, OneTimeTeardown attributes should be allowed as well.

**Comment by manfred-brands** [comment]
@Dreamescaper Good catch. The reverse hold for the TestMethodAccessibilityLevelAnalyzer (NUnit1026).
I updated the both TestMethodAccessibilityLevelAnalyzer to regoznize methods with (OneTime)SetUp/TearDown attribute as being 'TestMethod'. The pre-existing rule will now fire if these methods are non-public.
@mikkelbu I have rebased the branch on top of master to prevent nunit failures on the documentation.

**Comment by mikkelbu** [comment]
Good catch @Dreamescaper. Regarding TestMethodAccessibilityLevelAnalyzer then Setup/TearDown methods should either be public or protected (don't let the current wrong error message from the framework confuse you 😄 - this is corrected in https://github.com/nunit/nunit/commit/50babd1065afb63b58668f61449967d522bd9de4#diff-2db1dd498edafd51b9c83f1e99f5e0d5), so we need to handle Setup/TearDown a bit differently than the test methods.

**Comment by manfred-brands** [comment]
@mikkelbu Code updated. It now matches the `methodInfo.IsPublic || methodInfo.IsFamily` from NUnit.
With all the SemanticModel lookups for attributes I was thinking of converting the rule to a SymbolAnalyzer as mentioned in #270, but without any benchmark comparison I wouldn't know if it is any better. I verified that `GetTypeInfo` is cached in the roslyn code so it is might not be so bad.

The documentation says that one can configure the rule or suppress it, but that doesn't make sense as any violation means those tests will not run (properly). However the NUnit Documentation tests will fail if that section is changed even adding `This rule should not be disabled and any violations must be fixed as otherwise the tests do not get run at all.` fails the validation.

If you are happy, it can be merged.

**Comment by mikkelbu** [comment]
Thanks for the PR @manfred-brands. Currently, I don't mind having the sections about how to disable the diagnostic, but perhaps later we can improve on this. All diagnostics that are Errors will make tests not run - or fail in other manners.
Ps. I'll think about benchmarks for the analyzers.

**Pull request merged**
