### PR TITLE
fix: IndexOutOfRangeException threw by WithinUsageAnalyzer

### LINKED ISSUE #596: WithinUsageAnalyzer threw an exception of type 'System.IndexOutOfRangeException'
`NUnit.Analyzers="3.7.0"`

### Minimal reproducible case

```c#
using System.Collections;
using NUnit.Framework;

Assert.That(new DoubleCollection(1), Is.EqualTo(new DoubleCollection(2)).Within(0.001));

public class DoubleCollection : IEnumerable<double>
{
    public DoubleCollection(params double[] numbers) { }
    public IEnumerator<double> GetEnumerator() => throw new NotImplementedException();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

Error Message: `Analyzer 'NUnit.Analyzers.WithinUsage.WithinUsageAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.`

### PR DESCRIPTION
**Pull request by HenryZhang-ZHY**
fix #596

### CODE REVIEW

**Comment by HenryZhang-ZHY** [comment]
@dotnet-policy-service agree

**Comment by HenryZhang-ZHY** [comment]
PTAL @manfred-brands

**Review by manfred-brands — APPROVED** [review]
Thank you @HenryZhang-ZHY for not only reporting this, but also supplying the simple fix

**Comment by HenryZhang-ZHY** [comment]
Will this fix be released with version 3.8? If so, when is version 3.8 scheduled to be released?

**Comment by mikkelbu** [comment]
> Which version number will include this fix? When will it be released? @manfred-brands

@HenryZhang-ZHY  I think I'll create a version 3.7.1 and release it today or tomorrow (I just want to get one change

**Pull request merged**
