### PR TITLE
Update DisposeFieldsAndPropertiesInTearDownAnalyzer.cs to support Quit()

### PR DESCRIPTION
**Pull request by rhyous**
Update DisposeFieldsAndPropertiesInTearDownAnalyzer.cs to support Quit() as in Selenium that calls Dispose().

### CODE REVIEW

**Comment by rhyous** [comment]
@dotnet-policy-service agree [company="{Rhyous}"]

**Comment by mikkelbu** [comment]
Hi @rhyous 

Thanks for the contribution. As far as I can remember we chose the current method names to match the CA2000 rule. I'm not against adding `Quit` to the list, but are there any special case you are considering? As far as I can tell `Quit` is used by selenium-webdriver, but I'm unsure if there are other cases.

**Comment by rhyous** [comment]
Cool.

Yes, I am using Selenium. I also don't know of any other cases.

FYI, I checked for any pull requests for adding Quit() already, in case it had already been rejected, and I didn't see one. So I posted this suggestion/pull request and the unit team could either say yes, this is good, or no.

For now, I'm suppressing this. I'll accept whatever you think is best.

**Comment by manfred-brands** [comment]
This seems to be specific to a library you use.
Have you tried setting `dotnet_diagnostic.NUnit1032.additional_dispose_methods: Quit` in your `.editorconfig`?

**Comment by rhyous** [comment]
@M

> This seems to be specific to a library you use. Have you tried setting `dotnet_diagnostic.NUnit1032.additional_dispose_methods: Quit` in your `.editorconfig`?

I didn't try that. I just suppressed it. I will try that. Thanks!

**Comment by mikkelbu** [comment]
@rhyous No need for apologies. We have forgotten to add this information to the docs. I'll close this PR and then open a ticket about adding this to the docs of NUnit1032

**Pull request closed without merging**
