### PR TITLE
Add initial cake script

### PR DESCRIPTION
**Pull request by mikkelbu**
In order to get the initial script working I've temporarily commented
out the VSIX project from the solution file and commented out the nuget
task from nunit.analyzers.csproj.

Relates to #17.

### CODE REVIEW

**Comment by jnm2** [comment]
I remember an issue with 32-bit vs 64-bit msbuild and the VSIX project. I forget why, but I haven't had to work around it in a long time. This is what I'm doing, if it's helpful:

```cake
Task("Restore")
    .IsDependentOn("Clean")
    .Does(() => MSBuild(".", new MSBuildSettings().WithTarget("Restore")));

Task("Build")
    .IsDependentOn("Restore")
    .Does(() => MSBuild(".", new MSBuildSettings().WithTarget("Build")));

Task("Pack")
    .IsDependentOn("Build")
    .Does(() => MSBuild("Analyzer.Project.Name", new MSBuildSettings()
        .SetConfiguration(configuration)
        .WithTarget("Pack")
        .WithProperty("PackageOutputPath", "\"" + MakeAbsolute(packDir) + "\"")));
```

**Comment by jnm2** [comment]
Oh, I remember what I'm doing to work around it. In the `Release` Solution configuration, I uncheck the VSIX project under the 'build' column. In the other solution configuration I leave it checked so that F5 debugging works. Kind of a hack. 😝

**Comment by mikkelbu** [comment]
@jnm2 Did you change your comment (at least I got 2 emails with different content)?

I think that I ran in to the 32-bit vs 64-bit msbuild and the VSIX project issue. I cannot remember the error message, but a search sent me to this page [Unable to compile VSIX project that is a part of my solution using amd64 MSBuild from VS2015](https://social.msdn.microsoft.com/Forums/vstudio/en-US/fd220999-5761-475a-bf86-98dff6b35218/unable-to-compile-vsix-project-that-is-a-part-of-my-solution-using-amd64-msbuild-from-vs2015?forum=msbuild) and as a quick and dirty solution I just commented out the VSIX part.

**Comment by jnm2** [comment]
Yes, I realized the Cake snippet I posted first wasn't relevant because I didn't use it for debug builds. If the only issue is the msbuild process bitness, I remember using [`.SetMSBuildPlatform(MSBuildPlatform.x86)`](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettingsExtensions/1BEE8E3E) to solve that.

**Pull request merged**
